# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
project_name: local-weather
builds:
- main: ./cmd/local-weather/main.go
  env:
  - CGO_ENABLED=0
  goos:
      - darwin
      - linux
      - windows
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: local-weather

    # Github repository to push the tap to.
    github:
      owner: justinrsmith
      name: homebrew-local-weather-cli-go

    # Your app's description.
    # Default is empty.
    description: "Lightweight CLI for quickly checking the current weather."

    install: bin.install "local-weather"
scoop:
  bucket:
    owner: justinrsmith
    name: scoop-local-weather-cli-go
  description: "Lightweight CLI for quickly checking the current weather."
dockers:
  - binaries:
    - local-weather
  - image_templates:
    - "gcr.io/justin-dev-253220/local-weather-cli-go:latest"
    - "gcr.io/justin-dev-253220/local-weather-cli-go:{{ .Tag }}"
