name: build
on:
  push:
    branches:
      - master

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run Unit test
      run: |
        make deps
        make test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: |
        make deps
        make build
